[workspace]
channels = ["conda-forge"]
name = "agents-ss25"
platforms = ["win-64", "osx-arm64", "linux-64"]

[dependencies]
python = "3.13.*"
jupyter = "*"

[pypi-dependencies]
google-adk = "*"
pydantic = ">=2"
litellm = ">=1.73.1, <2"
